Sprint 6 solution
zephyr0021/java-kanban pull request #1
Opened 2024-12-28 16:38 UTC by zephyr0021

Выполнил задание 6 спринта

2024-12-29 16:06 UTC, z8q requested changes

2024-12-29 16:06 UTC, z8q commented on src/managers/InMemoryTaskManager.java
> +                historyManager.remove(subtaskId);
На методах clear данные из истории тоже могут удаляться

2024-12-30 17:45 UTC, zephyr0021 commented on src/managers/InMemoryTaskManager.java
> +                historyManager.remove(subtaskId);
Поправил. Нашел ошибку ее тоже поправил и покрыл тестами! :) Спасибо!

2024-12-31 13:54 UTC, z8q approved these changes

2025-01-19 11:16 UTC, merged